#!/bin/bash

cd /svnroot/git-dumps/mediawiki/core

git remote add origin ssh://gerrit.wikimedia.org:29418/mediawiki/core.git
git config --add remote.origin.push '+refs/heads/*:refs/heads/*'
git config --add remote.origin.push '+refs/tags/*:refs/tags/*'
git push -f origin
git push -f origin refs/notes/*
